---
# tasks file for gnome

- name: Install software using dnf
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: present
    exclude: "{{ gnome_exclude | default(omit) }}"
    allowerasing: true
  when:
    - ansible_facts['pkg_mgr'] in [ "dnf", "dnf5" ]

- name: Install software using package
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: present
  when:
    - ansible_facts['pkg_mgr'] not in [ "dnf", "dnf5" ]

- name: Start dbus-broker
  ansible.builtin.service:
    name: dbus-broker
    state: started
    enabled: true
  when:
    - ansible_facts['distribution'] == "Fedora"
    - ansible_facts['distribution_major_version'] | int > 33

- name: Start gnome display manager
  ansible.builtin.service:
    name: gdm
    state: started
    enabled: true

- name: Debug | Print gdm status after starting it.
  ansible.builtin.command: systemctl status gdm --no-pager -l
  changed_when: false
  failed_when: false
  register: gdm_status

- name: Debug | Show gdm status output.
  ansible.builtin.debug:
    var: gdm_status.stdout_lines
